all: tests clean dist

.PHONY: tests  # run test suite
tests:
	pip install -r requirements/ci.txt
	tox

.PHONY: clean # clean files generated by tests/package build process
clean:
	@rm -rf build dist
	@find . -name "*.pyc" -delete
	@git clean -xdf

#####

.PHONY: dist # build pip packages
dist: sdist bdist_wheel

.PHONY: sdist # build source distribution for the pip package
sdist:
	@python setup.py sdist

.PHONY: sdist # build binary (wheel) distribution for the pip package
bdist_wheel:
	@python setup.py bdist_wheel

#####

.PHONY: install # install the python package
install:
	@python setup.py install

.PHONY: release # upload source/binary distributions of the package to pypi
release: clean dist
	@twine upload dist/* -s -i $(IDENTITY)

.PHONY: test_release # TODO undocumented
test_release: clean dist
	@twine upload dist/* -r testpypi --skip-existing -s -i $(IDENTITY)

.PHONY: docs # build sphinx documentation
docs: clean
	@tox -r -e docs
